included:
    - Sources
    
excluded:
    - Tuist
    - Sources/App/AppDelegate.swift

disabled_rules:
    - todo
    - trailing_whitespace

opt_in_rules:
    - anonymous_argument_in_multiline_closure
    - anyobject_protocol
    - array_init
    - attributes
    - closure_body_length
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - comma_inheritance
    - contains_over_filter_count
    - contains_over_filter_is_empty
    - contains_over_first_not_nil
    - contains_over_range_nil_comparison
    - discouraged_none_name
    - discouraged_optional_boolean
    - discouraged_optional_collection
    - empty_collection_literal
    - empty_count
    - empty_string
    - explicit_init
    - explicit_self
    - fallthrough
    - file_name
    - file_name_no_space
    - first_where
    - flatmap_over_map_reduce
    - force_unwrapping
    - identical_operands
    - implicit_return
    - implicitly_unwrapped_optional
    - indentation_width
    - last_where
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - modifier_order
    - multiline_arguments
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - multiline_parameters
    - multiline_parameters_brackets
    - no_extension_access_modifier
    - operator_usage_whitespace
    - overridden_super_call
    - pattern_matching_keywords
    - return_value_from_void_function
    - self_binding
    - sorted_first_last
    - static_operator
    - toggle_bool
    - unneeded_parentheses_in_closure_argument
    - unowned_variable_capture
    - unused_declaration
    - unused_import
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - yoda_condition

# Configure
line_length: 140

nesting:
    type_level:
        warning: 3
    statement_level:
        warning: 5
    
identifier_name:
    excluded:
        - id
